function appendSectionReferences(doc)
%APPENDSECTIONREFERENCES Section 2 (Referenced Documents).

    import mlreportgen.dom.*

    append(doc, stg.word.heading("2. Referenced Documents", 2));

    refs = [
        "MIL-STD-498, Software Development and Documentation, 5 December 1994."
        "DI-IPSC-81440A, Data Item Description: Software Test Report (STR)."
        "IEEE Std 829-2008, Standard for Software and System Test Documentation."
        "AFI 63-101/20-101, Integrated Life Cycle Management."
        "AFI 33-360, Publications and Forms Management."
        "RTCA/DO-178C, Software Considerations in Airborne Systems."
        "RTCA/DO-330, Software Tool Qualification Considerations."
        "MathWorks, MATLAB Unit Testing Framework Documentation (matlab.unittest)."
    ];

    list = OrderedList();
    for k = 1:numel(refs)
        append(list, ListItem(char(refs(k))));
    end
    append(doc, list);

    append(doc, Paragraph(sprintf( ...
        "This artifact was generated by the matlabutscript test-suite generator operating " + ...
        "against the source item identified in 1.2. The tool itself is not formally qualified " + ...
        "under DO-330; outputs are intended to assist the test engineer of record, who remains " + ...
        "the approval authority for the report.")));
end
