function reportPath = generateHTMLReport(info, results, coverage, requirements, metadata, outDir)
%GENERATEHTMLREPORT Produce a self-contained MIL-STD-498 / IEEE 829 style
%Software Test Report (STR) following USAF documentation conventions.
%
%   The report is rendered as a single HTML file that embeds all CSS so it
%   may be archived as-is or printed to PDF without external dependencies.
%   Section structure is taken from the MIL-STD-498 Software Test Report
%   Data Item Description (DI-IPSC-81440A), tailored for IEEE 829 fields:
%
%       1. Scope
%       2. Referenced Documents
%       3. Overview of Test Results
%       4. Detailed Test Results
%       5. Test Log
%       6. Code Coverage Analysis
%       7. Configuration Items
%       8. Requirements Traceability Matrix
%       9. Notes (Acronyms / Glossary)
%      10. Approvals
%
%   Returns the absolute path to the generated file.

    arguments
        info        (1,1) struct
        results
        coverage    (1,1) struct
        requirements
        metadata    (1,1) struct
        outDir      (1,1) string
    end

    if ~isfolder(outDir)
        mkdir(outDir);
    end

    summary       = stg.summarizeResults(results);
    methodMeta    = stg.parseTestMethods(metadata.TestFile);
    enriched      = stg.html.joinResults(results, methodMeta);
    classification = string(metadata.Classification);

    parts = strings(0,1);
    parts(end+1) = "<!DOCTYPE html>";
    parts(end+1) = "<html lang=""en"">";
    parts(end+1) = "<head>";
    parts(end+1) = "    <meta charset=""UTF-8"">";
    parts(end+1) = "    <meta name=""viewport"" content=""width=device-width,initial-scale=1"">";
    parts(end+1) = "    <title>" + stg.escapeHtml(metadata.DocumentId + " - Software Test Report") + "</title>";
    parts(end+1) = "    <style>";
    parts(end+1) = stg.html.htmlStyles();
    parts(end+1) = "    </style>";
    parts(end+1) = "</head>";
    parts(end+1) = "<body>";
    parts(end+1) = "    <div class=""classification-banner top"">" + stg.escapeHtml(classification) + "</div>";
    parts(end+1) = "    <main class=""page"">";

    parts(end+1) = stg.html.coverPage(metadata, summary);
    parts(end+1) = stg.html.documentControl(metadata);
    parts(end+1) = stg.html.tableOfContents();
    parts(end+1) = stg.html.sectionScope(info, metadata);
    parts(end+1) = stg.html.sectionReferences(metadata);
    parts(end+1) = stg.html.sectionOverview(summary, coverage, metadata);
    parts(end+1) = stg.html.sectionDetailedResults(enriched);
    parts(end+1) = stg.html.sectionTestLog(metadata);
    parts(end+1) = stg.html.sectionCoverage(coverage);
    parts(end+1) = stg.html.sectionConfigItems(info, metadata);
    parts(end+1) = stg.html.sectionTraceability(enriched, requirements);
    parts(end+1) = stg.html.sectionNotes();
    parts(end+1) = stg.html.sectionApprovals(metadata);

    parts(end+1) = "        <div class=""footer"">";
    parts(end+1) = "            Document " + stg.escapeHtml(metadata.DocumentId) + " &bull; " + ...
                   stg.escapeHtml(metadata.GeneratedDate) + " &bull; " + ...
                   "Generated by matlabutscript / stg.generateHTMLReport";
    parts(end+1) = "        </div>";
    parts(end+1) = "    </main>";
    parts(end+1) = "    <div class=""classification-banner bottom"">" + stg.escapeHtml(classification) + "</div>";
    parts(end+1) = "</body>";
    parts(end+1) = "</html>";

    html = strjoin(parts, newline);

    [~, srcName] = fileparts(metadata.SourceName);
    reportPath = fullfile(outDir, "STR_" + string(srcName) + ".html");

    fid = fopen(char(reportPath), 'w');
    if fid < 0
        error("stg:generateHTMLReport:WriteFailed", ...
            "Could not write HTML report to '%s'.", reportPath);
    end
    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, html);
    reportPath = char(stg.absPath(reportPath));
end
