function css = htmlStyles()
%HTMLSTYLES Return the CSS used by the Software Test Report.
%   Inlined into the report so the artifact is self-contained for archival
%   in accordance with AFI 33-322 records-management practices.

    css = string(join([ ...
        "        :root {"
        "            --usaf-blue: #003a70;"
        "            --usaf-gold: #ffc20e;"
        "            --pass-green: #1e7e34;"
        "            --fail-red:   #b21f2d;"
        "            --warn-amber: #b8860b;"
        "            --ink:        #111;"
        "            --paper:      #fff;"
        "            --rule:       #ccd2d8;"
        "            --soft:       #f5f7fa;"
        "        }"
        "        * { box-sizing: border-box; }"
        "        html, body {"
        "            font-family: 'Times New Roman', Georgia, serif;"
        "            color: var(--ink); background: var(--paper);"
        "            margin: 0; padding: 0; line-height: 1.45; font-size: 11pt;"
        "        }"
        "        .page { max-width: 8.5in; margin: 0 auto; padding: 0.75in 0.9in; }"
        "        .classification-banner {"
        "            position: sticky; top: 0; z-index: 50;"
        "            background: var(--usaf-blue); color: #fff;"
        "            text-align: center; font-weight: bold; letter-spacing: 0.18em;"
        "            padding: 6px 0; font-family: Arial, sans-serif; font-size: 10pt;"
        "            text-transform: uppercase;"
        "        }"
        "        .classification-banner.bottom { position: static; }"
        "        h1, h2, h3, h4 { font-family: 'Cambria', 'Times New Roman', serif; color: var(--usaf-blue); }"
        "        h1 { font-size: 22pt; margin: 0 0 4pt; }"
        "        h2 { font-size: 16pt; border-bottom: 2px solid var(--usaf-blue); padding-bottom: 4px; margin-top: 28pt; }"
        "        h3 { font-size: 13pt; margin-top: 18pt; }"
        "        h4 { font-size: 11.5pt; margin-top: 14pt; color: var(--ink); }"
        "        .cover { text-align: center; padding: 1.4in 0 0.7in; border-bottom: 4px double var(--usaf-blue); margin-bottom: 0.6in; }"
        "        .cover .seal { font-size: 48pt; color: var(--usaf-gold); text-shadow: 0 0 1px var(--usaf-blue); margin-bottom: 8pt; }"
        "        .cover .title { font-size: 26pt; font-weight: bold; color: var(--usaf-blue); }"
        "        .cover .subtitle { font-size: 14pt; color: #444; margin-top: 6pt; letter-spacing: 0.08em; }"
        "        .cover .docid { font-size: 12pt; margin-top: 18pt; font-family: 'Courier New', monospace; }"
        "        .meta-table { width: 100%; border-collapse: collapse; margin: 16pt 0; }"
        "        .meta-table th, .meta-table td { border: 1px solid var(--rule); padding: 6px 10px; text-align: left; vertical-align: top; }"
        "        .meta-table th { background: var(--soft); width: 28%; font-weight: bold; }"
        "        table.results { width: 100%; border-collapse: collapse; margin: 10pt 0; font-size: 10pt; }"
        "        table.results th, table.results td { border: 1px solid var(--rule); padding: 5px 8px; vertical-align: top; }"
        "        table.results th { background: var(--usaf-blue); color: #fff; text-align: left; }"
        "        table.results tr:nth-child(even) { background: var(--soft); }"
        "        .verdict { display: inline-block; padding: 2px 10px; border-radius: 3px; font-weight: bold; font-family: Arial, sans-serif; font-size: 9.5pt; letter-spacing: 0.05em; }"
        "        .verdict.pass { background: var(--pass-green); color: #fff; }"
        "        .verdict.fail { background: var(--fail-red);  color: #fff; }"
        "        .verdict.incomplete, .verdict.warn { background: var(--warn-amber); color: #fff; }"
        "        .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 14pt 0; }"
        "        .kpi { border: 1px solid var(--rule); border-top: 3px solid var(--usaf-blue); padding: 10px 12px; background: var(--paper); }"
        "        .kpi .label { font-size: 9pt; text-transform: uppercase; letter-spacing: 0.08em; color: #666; }"
        "        .kpi .value { font-size: 22pt; font-weight: bold; color: var(--usaf-blue); }"
        "        .testcase { border: 1px solid var(--rule); border-left: 4px solid var(--usaf-blue); padding: 10px 14px; margin: 10pt 0; background: var(--paper); page-break-inside: avoid; }"
        "        .testcase.fail { border-left-color: var(--fail-red); background: #fdf3f4; }"
        "        .testcase.incomplete { border-left-color: var(--warn-amber); background: #fdf8e8; }"
        "        .testcase h4 { margin: 0 0 6pt; }"
        "        .testcase dl { display: grid; grid-template-columns: max-content 1fr; gap: 4px 12px; margin: 6pt 0; font-size: 10pt; }"
        "        .testcase dt { font-weight: bold; color: #555; }"
        "        pre.log, pre.code { background: #0e1116; color: #e6edf3; padding: 10px 12px; border-radius: 4px; font-size: 9pt; overflow-x: auto; }"
        "        pre.code { background: #f5f7fa; color: var(--ink); border: 1px solid var(--rule); }"
        "        .doc-control { font-size: 9.5pt; }"
        "        .toc ol { padding-left: 22px; }"
        "        .toc a { color: var(--usaf-blue); text-decoration: none; }"
        "        .footer { font-size: 9pt; color: #666; border-top: 1px solid var(--rule); padding-top: 6pt; margin-top: 24pt; text-align: center; }"
        "        .approval { width: 100%; border-collapse: collapse; margin-top: 14pt; }"
        "        .approval th, .approval td { border: 1px solid var(--ink); padding: 14px 10px; vertical-align: bottom; }"
        "        .approval th { background: var(--soft); }"
        "        .signblock { height: 0.55in; }"
        "        @media print {"
        "            .page { padding: 0.5in 0.6in; }"
        "            .classification-banner { position: static; }"
        "            h2 { page-break-before: always; }"
        "            .cover { page-break-after: always; }"
        "        }"
        ], newline));
end
