function html = sectionReferences(metadata)
%SECTIONREFERENCES Render Section 2 (Referenced Documents).

    refs = [
        "MIL-STD-498, Software Development and Documentation, 5 December 1994."
        "DI-IPSC-81440A, Data Item Description: Software Test Report (STR)."
        "IEEE Std 829-2008, Standard for Software and System Test Documentation."
        "AFI 63-101/20-101, Integrated Life Cycle Management."
        "AFI 33-360, Publications and Forms Management."
        "RTCA/DO-178C, Software Considerations in Airborne Systems and Equipment Certification."
        "RTCA/DO-330, Software Tool Qualification Considerations."
        "MathWorks, MATLAB Unit Testing Framework Documentation (matlab.unittest)."
    ];

    parts = strings(0,1);
    parts(end+1) = "        <section id=""sec-refs"">";
    parts(end+1) = "            <h2>2. Referenced Documents</h2>";
    parts(end+1) = "            <p>The following documents form a part of this STR to the extent specified herein.</p>";
    parts(end+1) = "            <ol>";
    for k = 1:numel(refs)
        parts(end+1) = "                <li>" + stg.escapeHtml(refs(k)) + "</li>"; %#ok<AGROW>
    end
    parts(end+1) = "            </ol>";
    parts(end+1) = "            <p>This artifact was generated by the matlabutscript test-suite generator " + ...
        "operating against the source item identified in &sect;1.2. The tool itself is not formally " + ...
        "qualified under DO-330; outputs are intended to assist the test engineer of record, who " + ...
        "remains the approval authority for the report.</p>";
    parts(end+1) = "        </section>";
    html = strjoin(parts, newline);
    if false, disp(metadata); end %#ok<UNRCH>  % accept arg without using
end
